@host = localhost
@port = 3000
@apiversion = api/v1

### Recuperar Um Categoria por ID
GET http://{{host}}:{{port}}/{{apiversion}}/categorias/4298ab9b-3f4e-41fb-a553-541708b31b17

### Recuperar Todas as Categorias
GET http://{{host}}:{{port}}/{{apiversion}}/categorias

### Inserir Uma Categoria
POST http://{{host}}:{{port}}/{{apiversion}}/categorias
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEyODcwNDIwLTUxZTUtNDliZS05ZGMwLWUxZGExZGY3NDlmMiIsIm5vbWUiOiJEYXZpZCIsImVtYWlsIjoiZGF2aWRwb250ZXNAZ21haWwuY29tIiwidGlwbyI6IkFETUlOSVNUUkFET1IiLCJpYXQiOjE3MDUzNjExOTYsImV4cCI6MTcwNTM2NDc5Nn0.sG_Zs8aQJ4Le7Db2owXkHagsjA2NShbKm7rilpxkIpc

{
    "nome":"Cozinha"
}

### Atualizar Categoria
PUT http://{{host}}:{{port}}/{{apiversion}}/categorias/4f8f367d-c4dc-4941-85e2-f3afcf9c77bb
Content-Type: application/json

{
    "id": "4f8f367d-c4dc-4941-85e2-f3afcf9c77bb",
    "nome":"Sala de Lazer"
    }

### Deletar Categoria
DELETE http://{{host}}:{{port}}/{{apiversion}}/categorias/4088c757-f153-41b9-b310-da0d1c63430c
